services:
  - type: web
    name: olympia-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:server
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
